# Generated by Django 5.1.3 on 2025-03-06 15:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_savedjob_job_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('job_type', models.CharField(choices=[('IN', 'Intern'), ('FT', 'Full-Time'), ('PT', 'Part-Time'), ('TP', 'Temporary'), ('CT', 'Contract')], default='FT', max_length=100)),
                ('job_description', models.TextField()),
                ('job_requirements', models.TextField()),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('expiry_time', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['expiry_time'],
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='applied_on',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_company',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_similarity',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='job_title',
        ),
        migrations.AddField(
            model_name='savedjob',
            name='status',
            field=models.CharField(choices=[('I', 'In Review'), ('A', 'Accepted'), ('R', 'Rejected')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='recruiter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recruiter'),
        ),
    ]
